var TEXT_GAMEOVER  = "CONGRATULATION! YOU WON!";
var TEXT_LOSE = "SORRY, THE PLAYER %s WON THIS GAME";
var TEXT_SCORE     = "YOUR SCORE";
var TEXT_RESTART   = "RESTART";
var TEXT_ARE_SURE = "ARE YOU SURE?";
var TEXT_SELECT_PLAYERS = "SELECT THE NUMBER OF PLAYERS!";
var TEXT_SELECT_COLOR = "SELECT A COLOR";
var TEXT_TUTORIAL1 = "WELCOME TO FOUR COLORS! MATCH CARDS BY COLOR OR NUMBER AND BE THE FIRST TO GET RID OF THEM!";
var TEXT_TUTORIAL2 = "ACTION CARDS WILL MIX THE GAME UP!\n\nDRAW TWO FORCES THE NEXT PLAYER TO PICK TWO CARDS AND FORFEIT THE TURN";
var TEXT_TUTORIAL3 = "SKIP CARD STOPS THE NEXT PLAYER";
var TEXT_TUTORIAL4 = "REVERSE CARD SWITCHES THE GAME WISE";
var TEXT_TUTORIAL5 = "THE WILD CARD CAN BE PLACED ON ANY CARD AT ANY TIME AND ALLOWS YOU TO CHANGE THE COLOR TO PLAY ";
var TEXT_TUTORIAL6 = "THE WILD DRAW FOUR IS A SPECIAL WILD THAT ALLOWS YOU TO CHANGE THE COLOR AND FORCES THE NEXT PLAYER TO PICK 4 CARDS. TO USE THIS CARD YOU MUST HAVE NO OTHER ALTERNATIVE CARDS TO PLAY";
var TEXT_TUTORIAL7 = "DO NOT FORGET TO PRESS THE 1 BUTTON WHEN YOU'LL HAVE ONLY ONE CARD LEFT OR YOU'LL PICK 2 PENALTY CARDS!";
var TEXT_PLAYER_1 = "PLAYER 1";
var TEXT_PLAYER_2 = "PLAYER 2";
var TEXT_PLAYER_3 = "PLAYER 3";
var TEXT_PLAYER_4 = "PLAYER 4";
var TEXT_ALERT_1 = "YOU MUST PRESS ' 1 ' BUTTON WHEN YOU HAVE JUST ONE CARD. TWO CARDS PENALITY";
var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_DEVELOPED = "DEVELOPED BY";


var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";

